### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by koliyo** [marians/rebrow#19]
For example
```
    <td><a href="{{ key|urlsafe_base64 }}/">{{ key }}</a></td>
  File "runserver.py", line 274, in urlsafe_base64_encode
    s = s.encode('utf8')
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by earthgecko** [comment]
Hi @koliyo 

The readme.md on the front page of this repo specifically states:

* Runs in Python 2.7

It will work on Python 2.7

**Comment by marians** [comment]
If someone requires Python 3 support, I'd welcome a pull request. However I am not sure we can simply support python 2.7 and 3 at the same time, so probably that would mean dropping support for 2.7.

**Comment by mrgnw** [comment]
It looks like https://github.com/ali-tny/rebrow/commit/1d86af66cd3ebf5c178f65d48984d930488e145f addresses the encoding issue.

**Comment by earthgecko** [comment]
@mrgnw that ali-tny@1d86af6 will not work with Python 2.7 I do not think as it is.

@marians rebrow can work with both Python 2.7 and 3 I have a copy that is working on both, however mine copy is somewhat modified but the gist of getting it to work on both is:

```python

from sys import version_info

python_version = int(version_info[0])
...
...
        if python_version == 2:
            dump = r.dump(key)
        dump_key = key.decode('utf-8')
        if python_version == 3:
            dump = r.dump(dump_key)
...
    if python_version == 2:
        t = r.type(key)
    if python_version == 3:
        key = dump_key
        t = r.type(key).decode('utf-8')
...
...
    s_original = s
    if isinstance(s, Markup):
        s = s.unescape()
    elif isinstance(s, bytes):
        s = s.decode('utf-8')
    s = s.encode('utf8')
    s = base64.urlsafe_b64encode(s)

    if python_version == 3:
        decoded_s = s.decode('utf-8')
        s = decoded_s

    return Markup(s)
```

And that should suffice.

**Comment by mrgnw** [comment]
The above comments were very helpful!

I found that we can also use redis decode_responses to address encoding issues, at least for `def keys(...)`:

https://github.com/marians/rebrow/blob/e7bdb0030c8fab48160f1d0a9f0cb7064a4a3e16/runserver.py#L164


```python
r = redis.StrictRedis(host=host, port=port, db=db, charset="utf-8", decode_responses=True)
```
